// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from '../../../supabase.config.js';

// const SUPABASE_URL = "https://mjxwvrezxlxgwthgdwma.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qeHd2cmV6eGx4Z3d0aGdkd21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzQyMjQsImV4cCI6MjA2MjIxMDIyNH0.2W6Gk7WWkXeiGZDjXFSnSODgkJYObu74kd7yizpgzGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);